name: FanCode SDET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        mkdir -p reports
        pytest -v --junitxml=reports/junit.xml --html=reports/report.html --self-contained-html
      continue-on-error: true

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.python-version }}
        path: reports/
        retention-days: 7

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Tests (Python ${{ matrix.python-version }})
        path: reports/junit.xml
        reporter: java-junit
        fail-on-error: false

  docker-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'  # Skip on scheduled runs
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Build and test with Docker
      run: |
        mkdir -p reports
        docker build -t fancode-sdet .
        docker run --rm -v $(pwd)/reports:/app/reports fancode-sdet || true
        
    - name: Upload Docker reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-reports
        path: reports/
        retention-days: 7

  notify:
    runs-on: ubuntu-latest
    needs: [test, docker-test]
    if: always()
    steps:
      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports-3.11
          path: reports/
      - name: Download docker reports
        uses: actions/download-artifact@v4
        with:
          name: docker-reports
          path: reports/docker/
      - name: Notify workflow completion
        run: |
          echo "FanCode SDET workflow completed."
          echo "Test job status: ${{ needs.test.result }}"
          echo "Docker-test job status: ${{ needs.docker-test.result }}"
      - name: Send comprehensive test report via email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: FanCode SDET Comprehensive Test Results
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            The FanCode SDET workflow has completed.

            Test job status: ${{ needs.test.result }}
            Docker-test job status: ${{ needs.docker-test.result }}

            Please find the attached test reports.
          attachments: |
            reports/report.html
            reports/docker/report.html